name: sharedchat

services:
  frontend:
    build: 
      context: ./apps/frontend
    ports:
      - "80:8000"
    depends_on:
      - auth-service
      - db

  auth-service:
    build:
      context: ./apps/auth-service
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/signin"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:18rc1-alpine3.22
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: