name: sharedchat

services:
  frontend:
    build: 
      context: ./apps/frontend
    ports:
      - "80:8000"
    depends_on:
      - auth-service
      - db

  auth-service:
    build:
      context: ./apps/auth-service
    env_file:
      - ./apps/auth-service/.env
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/signin"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:18rc1-alpine3.22
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
      - ./scripts/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9.8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin-data: